// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/novica/[novica_name]": InferRoute<import("./src/app/novica/[novica_name]/routeType").RouteType>;
    "/uredi/[novica_name]": InferRoute<import("./src/app/uredi/[novica_name]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/nastavitve/novice": StaticRoute;
    "/nastavitve": StaticRoute;
    "/nastavitve/profil": StaticRoute;
    "/novice": StaticRoute;
    "/": StaticRoute;
    "/prijava": StaticRoute;
    "/s3": StaticRoute;
  }
}
