// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


import { type RouteType as Route_0 } from "./src/app/edit/[articleUrl]/routeType";
import { type RouteType as Route_1 } from "./src/app/novicka/[novicka_name]/routeType";
import type { InferRoute, StaticRoute } from "next-typesafe-url";

declare module "@@@next-typesafe-url" {
  
  interface DynamicRouter {
    "/edit/[articleUrl]": InferRoute<Route_0>;
    "/novicka/[novicka_name]": InferRoute<Route_1>;
  }

  interface StaticRouter {
    "/account": StaticRoute;
    "/": StaticRoute;
    "/search": StaticRoute;
    "/testing": StaticRoute;
  }
}
