// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/novicka/[novicka_name]": InferRoute<import("./src/app/novicka/[novicka_name]/routeType").RouteType>;
    "/uredi/[article_url]": InferRoute<import("./src/app/uredi/[article_url]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/novicke": StaticRoute;
    "/": StaticRoute;
    "/prijava": StaticRoute;
    "/racun/novicke": StaticRoute;
    "/racun": StaticRoute;
  }
}
